### ISSUE TITLE
Allow to run smoke test orchestrator on any network

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1482]
Smoke test orchestrator is a efficient way to quickly tests the cross-chain features in a E2E basis.
There might be network, or parameter update in the feature that requires testing the cross-chain features for a specific network.

Running the orchestrator operations for a specific network would be beneficial.

Two required changes I see:

- Making smoke tests execution configurable, allowing executing from the command line only the ERC20 deposit test for example without having the need to comment line of codes.
- Make the network used configurable, this requires having the ability to customize:
  - RPC of the external chains
  - Hot wallet private keys to interact with network
  - Addresses of the different contract (USDT, etc... )

Ideally we can end up with a single command line that allow to run specific test:
```
make orchestrator --config testnet.yml
```
`testnet.yml`
```yaml
zeta-rpc: ...
btc-rpc: ...
evm-rpc: ...
hotkey: ...
tests:
 - ethersDeposits
 - erc20Deposits
 - crosschainSwaps
```
Eventally hotkeys are only provided through env vars
