### ISSUE TITLE
completion time in redelegations 

### ISSUE THREAD

**Issue by mingyuanlee** [zeta-chain/node#1826]
Hi guys, I'm not sure if this is a bug or I misunderstood something.

When I redelegate and query the redelegations api, I got:
```
- entries:
  - balance: "1000000000000000"
    redelegation_entry:
      completion_time: "2024-03-04T23:21:08.654247263Z"
      creation_height: 3855015
      initial_balance: "1000000000000000"
      shares_dst: "1041020302137042.846061034065956794"
  - balance: "1000000000000000"
    redelegation_entry:
      completion_time: "2024-03-05T20:40:26.384759672Z"
      creation_height: 3867769
      initial_balance: "1000000000000000"
      shares_dst: "1041020302137042.846061034065956794"
  redelegation:
    delegator_address: zeta1l0llh37dph06ma4elr2g3um3c2wfm7mqqn85tm
    entries: null
    validator_dst_address: zetavaloper1t5u55hsz48pgmks06fyy3hklt5urdzgx07ncx2
    validator_src_address: zetavaloper1p3emgemv8q0fmtw70kfzwecmcvyd9ztqlzudwn
```

Why is the completion time in the future? Today is March 1st and shouldn't redelegation happens immediately?
