### ISSUE TITLE
Early ballot deletion can result in missed inbound observation, mitigation needed

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#3511]
**Describe the incident**
A missed inbound was detected on Feb. 9th in Base chain mainnet. The inbound was [this deposit](https://basescan.org/tx/0x66b59ad844404e91faa9587a3061e2f7af36f7a7a1a0afaca3a2efd811bc9463) ([cctx](https://zetachain-mainnet-api.itrocket.net/zeta-chain/crosschain/inboundHashToCctxData/0x66b59ad844404e91faa9587a3061e2f7af36f7a7a1a0afaca3a2efd811bc9463))

All the `zetaclients` had posted their inbound votes successfully, but there was no CCTX registered in `zetacore`.

How it was resolved:
An inbound tracker was manually created and submitted to `zetacore`, and the CCTX was then finalized right away: [the CCTX](https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/crosschain/inboundHashToCctxData/0x66b59ad844404e91faa9587a3061e2f7af36f7a7a1a0afaca3a2efd811bc9463)

The root cause:
One of the votes posted by zetaclient was this: [the inbound vote](https://explorer.zetachain.com/cosmos/tx/E7FAA84651B83ED1EFDC00437C3781C3CA8140F54332A8F59059E1A1E9D41486)

A pending ballot was supposed to be created in chain state before `v27`, but the ballot was not found during the incident. So we guess that the newly installed ballot deletion logic had removed it (nothing else deletes ballot).

Basically, a ballot, once created as pending, takes at least `6/9` votes to finalize. If a pending ballot (e.g. got 5/9 votes) is not able to get enough votes within `BallotMaturityBlocks`, it will be deleted and all existing votes were lost. Late votes may also come in and re-create the ballot, but they won't be able to finalize it due to the lack of voters.

In general, an inbound ballot could stay in pending status for longer time (than `BallotMaturityBlocks`)  due to any type of delay (RPC latency, zetaclient offline, etc.)

<details>
<summary>ballot status around finalization</summary>

### 6971932

```
ballot_identifier: 0x66ef65e8c1dc5008effc66d5ff561e4d4aa1e0fe201b1bd3f8ba4097b3378d50
ballot_status: BallotInProgress
observation_type: InboundTx
voters:
- vote_type: NotYetVoted
  voter_address: zeta1p0uwsq4naus5r4l7l744upy0k8ezzj84mn40nf
- vote_type: SuccessObservation
  voter_address: zeta1l07weaxkmn6z69qm55t53v4rfr43eys4cjz54h
- vote_type: NotYetVoted
  voter_address: zeta1t0uj2z93jd2g3w94zl3jhfrn2ek6dnuk3v93j9
- vote_type: SuccessObservation
  voter_address: zeta1rhj4pkp7eygw8lu9wacpepeh0fnzdxrqr27g6m
- vote_type: SuccessObservation
  voter_address: zeta1t5pgk2fucx3drkynzew9zln5z9r7s3wqqyy0pe
- vote_type: NotYetVoted
  voter_address: zeta1hjct6q7npsspsg3dgvzk3sdf89spmlpf7rqmnw
- vote_type: SuccessObservation
  voter_address: zeta1cxj07f3ju484ry2cnnhxl5tryyex7gev0yzxtj
- vote_type: NotYetVoted
  voter_address: zeta1k6vh9y7ctn06pu5jngznv5dyy0rltl2qp0j30g
- vote_type: SuccessObservation
  voter_address: zeta19jr7nl82lrktge35f52x9g5y5prmvchmk40zhg
```

### 6971933

```
ballot_identifier: 0x66ef65e8c1dc5008effc66d5ff561e4d4aa1e0fe201b1bd3f8ba4097b3378d50
ballot_status: BallotFinalized_SuccessObservation
observation_type: InboundTx
voters:
- vote_type: NotYetVoted
  voter_address: zeta1p0uwsq4naus5r4l7l744upy0k8ezzj84mn40nf
- vote_type: SuccessObservation
  voter_address: zeta1l07weaxkmn6z69qm55t53v4rfr43eys4cjz54h
- vote_type: NotYetVoted
  voter_address: zeta1t0uj2z93jd2g3w94zl3jhfrn2ek6dnuk3v93j9
- vote_type: SuccessObservation
  voter_address: zeta1rhj4pkp7eygw8lu9wacpepeh0fnzdxrqr27g6m
- vote_type: SuccessObservation
  voter_address: zeta1t5pgk2fucx3drkynzew9zln5z9r7s3wqqyy0pe
- vote_type: SuccessObservation
  voter_address: zeta1hjct6q7npsspsg3dgvzk3sdf89spmlpf7rqmnw
- vote_type: SuccessObservation
  voter_address: zeta1cxj07f3ju484ry2cnnhxl5tryyex7gev0yzxtj
- vote_type: NotYetVoted
  voter_address: zeta1k6vh9y7ctn06pu5jngznv5dyy0rltl2qp0j30g
- vote_type: SuccessObservation
  voter_address: zeta19jr7nl82lrktge35f52x9g5y5prmvchmk40zhg
```

### 6971934

```
ballot_identifier: 0x66ef65e8c1dc5008effc66d5ff561e4d4aa1e0fe201b1bd3f8ba4097b3378d50
ballot_status: BallotFinalized_SuccessObservation
observation_type: InboundTx
voters:
- vote_type: SuccessObservation
  voter_address: zeta1p0uwsq4naus5r4l7l744upy0k8ezzj84mn40nf
- vote_type: SuccessObservation
  voter_address: zeta1l07weaxkmn6z69qm55t53v4rfr43eys4cjz54h
- vote_type: SuccessObservation
  voter_address: zeta1t0uj2z93jd2g3w94zl3jhfrn2ek6dnuk3v93j9
- vote_type: SuccessObservation
  voter_address: zeta1rhj4pkp7eygw8lu9wacpepeh0fnzdxrqr27g6m
- vote_type: SuccessObservation
  voter_address: zeta1t5pgk2fucx3drkynzew9zln5z9r7s3wqqyy0pe
- vote_type: SuccessObservation
  voter_address: zeta1hjct6q7npsspsg3dgvzk3sdf89spmlpf7rqmnw
- vote_type: SuccessObservation
  voter_address: zeta1cxj07f3ju484ry2cnnhxl5tryyex7gev0yzxtj
- vote_type: SuccessObservation
  voter_address: zeta1k6vh9y7ctn06pu5jngznv5dyy0rltl2qp0j30g
- vote_type: SuccessObservation
  voter_address: zeta19jr7nl82lrktge35f52x9g5y5prmvchmk40zhg
```

</details>

**Expected Outcome**
A description of what outcome you are seeking.
